#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Usage:
    gitbook (fetch | make | push) <book_id>
    gitbook all BOOKID BOOKIDEND
"""

from docopt import docopt
import github3
import sh

from gitenberg import Book
from gitenberg import __version__

def do_all(book_id_start, book_id_end):
    for book_id in xrange(int(book_id_start), int(book_id_end)):
        try:
            fetch(book_id)
            make(book_id)
            push(book_id)
        except sh.ErrorReturnCode_23:
            print "This book doesn't exist at this path on pg servers"
        except github3.GitHubError as e:
            if e.code == 422:
                print "This repo already exists!"
                continue
            else:
                raise exception




if __name__ == '__main__':
    arguments = docopt(__doc__, version=__version__)

    if arguments['<book_id>'] is not None:
        book = Book(arguments['<book_id>'])

    if arguments['fetch']:
        book.fetch()

    elif arguments['make']:
        book.make()

    elif arguments['push']:
        book.push()

    elif arguments['all']:
        do_all(arguments['BOOKID'], arguments['BOOKIDEND'])
