#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Usage:
    gitbook (fetch | make | push) BOOKID
    gitbook all BOOKID BOOKIDEND
"""

from docopt import docopt
import github3
import sh

from gitenberg import fetch, make, push
from gitenberg import CantPathHereException
from gitenberg import __version__

def do_all(book_id_start, book_id_end):
    for book_id in xrange(int(book_id_start), int(book_id_end)):
        try:
            fetch(book_id)
            make(book_id)
            push(book_id)
        except CantPathHereException:
            print "Can't path to book {id}".format(id=book_id)
        except sh.ErrorReturnCode_23:
            print "This book doesn't exist at this path on pg servers"
        except github3.GitHubError as e:
            if e.code == 422:
                print "This repo already exists!"
                continue
            else:
                raise exception


if __name__ == '__main__':
    arguments = docopt(__doc__, version=__version__)

    if arguments['fetch']:
        fetch(arguments['BOOKID'])

    elif arguments['make']:
        make(arguments['BOOKID'])

    elif arguments['push']:
        push(arguments['BOOKID'])

    elif arguments['all']:
        do_all(arguments['BOOKID'], arguments['BOOKIDEND'])
