#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Usage:
    gitbook (fetch | make | push) <book_id>
    gitbook all BOOKID BOOKIDEND
"""

from docopt import docopt
import github3
import sh

from gitenberg import Book
from gitenberg import __version__

def do_all(book_id_start, book_id_end):
    for book_id in xrange(int(book_id_start), int(book_id_end)):
        book = Book(book_id)
        book.all()


if __name__ == '__main__':
    arguments = docopt(__doc__, version=__version__)

    if arguments['<book_id>'] is not None:
        book = Book(arguments['<book_id>'])
        book.parse_book_metadata()

    if arguments['fetch']:
        book.fetch()

    elif arguments['make']:
        book.make()

    elif arguments['push']:
        book.push()

    elif arguments['all']:
        do_all(arguments['BOOKID'], arguments['BOOKIDEND'])
